# Generated by Django 3.2.9 on 2021-11-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joinus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
                ('interest', models.CharField(choices=[('Watching Movies', 'Watching Movies'), ('Singing', 'Singing'), ('Gardening', 'Gardening'), ('Reading Books', 'Reading Books'), ('Playing Cricket', 'Playing Cricket')], max_length=25)),
                ('comment', models.TextField()),
            ],
        ),
    ]
