# Generated by Django 3.1.3 on 2021-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/photos')),
                ('title', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/photos')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=1)),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('tw_link', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('insta_link', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('linked_link', models.URLField(blank=True, null=True, verbose_name='Linked URL')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/videos')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'Blocked'), ('4', 'Spam')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.AlterField(
            model_name='joinus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='interest',
            field=models.CharField(choices=[('', 'Select Interest '), ('Watching Movies', 'Watching Movies'), ('Singing', 'Singing'), ('Gardening', 'Gardening'), ('Reading Books', 'Reading Books'), ('Playing Cricket', 'Playing Cricket')], max_length=25),
        ),
    ]
