# Generated by Django 3.1.3 on 2021-11-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usa_app', '0002_auto_20211119_1648'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
