# Generated by Django 2.2 on 2021-11-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usa_app', '0004_setting'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='setting',
            table='setting',
        ),
    ]
