# Generated by Django 3.2.9 on 2021-11-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usa_app', '0007_auto_20211125_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='website_link',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
