# Generated by Django 3.2.9 on 2021-11-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usa_app', '0008_auto_20211125_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
